const MATERIAL_ALIASES: Record<string, string> = {
  "clean-water": "water",
  "cooling-water": "water",
  feedwater: "water",
  "bulk-agent": "water",
  "disinfectant-or-fuel": "ethanol",
  fuel: "fuel",
  "coal-or-oil-fuel": "fuel",
  "aviation-fuel": "fuel",
  "cordwood-or-biomass-fuel": "biomass-fuel",
  cordwood: "biomass-fuel",
  "dry-tinder-and-kindling": "tinder",
  "hardwood-ash": "wood-ash",
  "animal-or-plant-fat": "fat",
  lubricant: "lubricant",
  lubricants: "lubricant",
  "drawing-lubricants": "lubricant",
  grease: "lubricant",
  aluminium: "aluminium",
  "aluminium-alloys": "aluminium",
  "aluminium-for-rotors": "aluminium",
  "aluminium-rod-for-stranding": "aluminium",
  "aluminium-tower-sections": "aluminium",
  "copper-or-aluminium-conductors": "conductors",
  "aluminium-and-steel-conductors": "conductors",
  "copper-wire": "copper",
  "copper-buswork": "copper",
  "cathode-copper": "copper",
  "copper-ore-malachite-chalcopyrite-after-roasting": "copper-ore",
  "cordage-fibres": "cordage-fiber",
  "bast-fibre-plants": "cordage-fiber",
  "cellulosic-fibre": "plant-fiber",
  "animal-sinew": "sinew",
  "clay-and-temper": "clay",
  "clay-or-turf": "clay",
  "charcoal-powder": "charcoal",
  "abrasive-stone": "abrasive",
  "abrasive-for-platform-preparation": "abrasive",
  "hard-stone-fulcrum": "stone",
  "crushed-stone": "stone",
  "boiler-plate-steel": "steel",
  "boiler-grade-steel": "steel",
  "alloy-steels": "steel",
  "central-office-steel": "steel",
  "electrical-steel": "steel",
  "go-silicon-steel": "electrical-steel",
  "alloying-elements-optional": "alloying-elements",
  "flux-optional": "flux",
  "hardwood-lumber": "wood",
  "hardwood-timber": "wood",
  "handle-wood": "wood",
  "hardwood-or-metal-for-sheave": "wood-or-metal",
  "glass-envelopes": "glass",
  "glass-or-polycarbonate": "glass-or-polycarbonate",
  "glass-tubing-and-press": "glass",
  "food-grade-vessels": "containers",
  "food-ingredients": "food",
};

const MATERIAL_LABELS: Record<string, string> = {
  abrasive: "Abrasive",
  aluminium: "Aluminium",
  "alloying-elements": "Alloying elements",
  "biomass-fuel": "Biomass fuel",
  charcoal: "Charcoal",
  clay: "Clay",
  conductors: "Electrical conductors",
  containers: "Containers",
  copper: "Copper",
  "copper-ore": "Copper ore",
  "cordage-fiber": "Cordage fibre",
  "electrical-steel": "Electrical steel",
  ethanol: "Ethanol or disinfectant fuel",
  fat: "Animal or plant fat",
  flux: "Flux",
  food: "Food ingredients",
  fuel: "Fuel",
  glass: "Glass",
  "glass-or-polycarbonate": "Glass or polycarbonate",
  lubricant: "Lubricant",
  "plant-fiber": "Plant fibre",
  sinew: "Animal sinew",
  steel: "Steel",
  stone: "Stone",
  tinder: "Tinder and kindling",
  water: "Water",
  wood: "Wood",
  "wood-ash": "Wood ash",
  "wood-or-metal": "Wood or metal",
};

export function materialKey(name: string): string {
  const base = name
    .trim()
    .toLowerCase()
    .replace(/&/g, " and ")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
  return MATERIAL_ALIASES[base] ?? base;
}

export function materialLabel(key: string, fallback: string): string {
  return MATERIAL_LABELS[key] ?? fallback.trim();
}
